name: ainaqah
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^4.6.21

  # BASE
  intl: 0.17.0

  # FIREBASE PACKAGES
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_remote_config: ^3.0.3

  # UI
  flutter_vector_icons: ^2.0.0
  dotted_border: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  otp_text_field: ^1.1.3
  flutter_staggered_grid_view: ^0.6.2
  country_code_picker: ^2.0.2
  html: ^0.15.0
  flutter_html: ^2.2.1
  package_info_plus: ^1.4.2
  clippy_flutter: 2.0.0-nullsafety.1
  change_app_package_name: ^1.1.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.4.1

  # STATE MANAGEMENT
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6+4

  # # ADS
  # google_mobile_ads: ^2.1.0

  # # VIDEOS
  # video_player: ^2.4.7

  # IMAGES
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2
  photo_view: ^0.14.0

  # AUTHENTICATION
  google_sign_in: ^5.4.2
  the_apple_sign_in: ^1.1.1

  # CONNECTIVITY
  http: ^0.13.5
  #  connectivity: ^3.0.6
  share: ^2.0.4

  #TOOLS
  google_fonts: ^3.0.1

  # WEB TOOLS
  webview_flutter: ^2.3.1

  # PAYMENTS
  # flutter_stripe: ^6.0.0
  # flutterwave_standard: ^1.0.4
  # razorpay_flutter: ^1.3.3
  # flutter_paystack: ^1.0.6

  # LAUNCH URL
  url_launcher: ^6.1.6

  flutter_localizations:
    sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7+3
  build_runner: ^2.3.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/ainaqah/
    - lang/
    - assets/
    - images/ainaqah/Christmas/
    - images/ainaqah/Halloween/
